pip install pycparser
pip install cffi
pip install setuptools
pip install six
pip install certifi
pip install charset-normalizer
pip install click
pip install cryptography
pip install idna
pip install mypy-extensions
pip install numpy
pip install packaging
pip install pathspec
pip install platformdirs
pip install pycountry
pip install pyasn
pip install python-dateutil
pip install pytz
pip install tomli
pip install urllib3
pip install black
pip install Faker
pip install PGPy==0.6.0
pip install psycopg-binarypip
pip install pandas
pip install requests
pip install schwifty
pip install --force-reinstall src/cstar-cli-core
pip install --no-deps --force-reinstall src/cstar-cli