parameters:
    - name: 'xk6CacheKey'
      type: string
    - name: 'k6Version'
      type: string
      default: v0.45.1
    - name: 'xk6Extensions'
      type: string
      default: '--with github.com/avitalique/xk6-file@latest --with github.com/szkiba/xk6-dotenv@latest'

jobs:
    - job: xk6Build
      displayName: Building xk6
      timeoutInMinutes: 0
      steps:
          - task: Cache@2
            inputs:
                key: '$(xk6CacheKey)'
                path: '$(Build.SourcesDirectory)/xk6'
                cacheHitVar: XK6_RESTORED
            displayName: Retrieve xk6 from Cache
          - script: |
                mkdir xk6
                docker run --rm -u "$(id -u):$(id -g)" -v "${PWD}/xk6:/xk6" grafana/xk6:latest build ${{ parameters.k6Version }} --output xk6 ${{ parameters.xk6Extensions }}
            displayName: Build xk6 binary
            condition: ne(variables.XK6_RESTORED, 'true')
