# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: 'SCRIPT'
    displayName: 'Script name'
    type: string
    values:
      - putTokenMockedPdv
  - name: 'TARGET_ENV'
    displayName: 'Target Environment'
    type: string
    default: 'uat'
    values:
      - 'dev'
      - 'uat'

steps:
  - script: |
       docker pull grafana/k6:latest
    displayName: Pull k6 image
  - script: |
      pwd
      ls -lrt
      docker run -i \
        -v $(pwd):/app \
        -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
        grafana/k6:latest \
        run /app/test/performance/${{ parameters.SCRIPT }}.js \
    displayName: Run k6 ${{ parameters.SCRIPT }}
  - script: |
      docker ps -a
      CONTAINER_ID=$(docker ps -l -q) 
      docker cp $CONTAINER_ID:$(pwd)/app/performancetest-result.xml $(pwd)/performancetest-result.xml 
      pwd
      ls -lrt
    displayName: Retrieve result file
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/performancetest-result.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true

