# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: 'SCRIPT'
    displayName: 'Script name'
    type: string
    values:
      - putTokenMockedPdv
  - name: 'TARGET_ENV'
    displayName: 'Target Environment'
    type: string
    default: 'uat'
    values:
      - 'dev'
      - 'uat'

steps:
  - script: |
      apt-get -y update && apt-get -y upgrade
      apt install -y python3-pip
      curl -sSL https://install.python-poetry.org | python3 -
      curl -L https://github.com/pagopa/cstar-cli/archive/refs/heads/main.zip -o cstar-cli.zip
      unzip cstar-cli.zip
      cd cstar-cli-main
      pip install --force-reinstall src/cstar-cli-core
      pip install --no-deps --force-reinstall src/cstar-cli
    displayName: Set environment
  - script: |
      cd src/cstar-cli/
      python cst idpay idpaydataset \
              --action dataset_and_transactions \
              --env ${{ parameters.TARGET_ENV }} \
              --out-dir .\generated  \
              --num-fc 10 \
              --trx-per-fc 1 \
              --start-datetime 2023-02-27T20:30:00.000Z \
              --mcc 1234 \
              --PM-salt SALT123
      cd ../../../
    displayName: Retrieve resource from cstar-cli
  - script: |
       docker pull grafana/k6:latest
    displayName: Pull k6 image
  - script: |
      docker run -i \
        --name ksixtests \
        --user $UID \
        -v $(pwd):/app \
        --workdir "/app" \
        -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
        grafana/k6:latest \
        run /app/test/performance/${{ parameters.SCRIPT }}.js
    displayName: Run k6 ${{ parameters.SCRIPT }}
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/performancetest-result.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true

