# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

variables:
  # Python version: 3.10
  pythonVersion: '3.10'

  # Folder name of this sub-repository
  working-dir: '.'

  # Project root folder
  projectRoot: $(System.DefaultWorkingDirectory)/$(working-dir)

parameters:
  - name: 'SCRIPT'
    displayName: 'Script name'
    type: string
    values:
      - putTokenMockedPdv
      - putTokenPdv
      - idpayOnboardingAPI
      - ioPutEnrollInstrumentIssuer
      - ioPutEnrollIban
      - rtdTransactionsFile
  - name: 'TARGET_ENV'
    displayName: 'Target Environment'
    type: string
    default: 'uat'
    values:
      - 'dev'
      - 'uat'
  - name: 'SCENARIO_TYPE_ENV'
    displayName: 'Scenario type'
    type: string
    default: 'rampingArrivalRate'
    values:
      - 'rampingArrivalRate'
      - 'perVuIterations'
  - name: 'VIRTUAL_USERS_ENV'
    displayName: 'Number of virtual users (1 - 100 000)'
    type: number
  - name: 'STAGE_NUMBER_ENV'
    displayName: 'Number of ramping stages (min: 3)'
    type: number
    default: 3
  - name: 'DURATION_PER_VU_ITERATION'
    displayName: 'Maximum duration in seconds for the perVuIterations-type scenario'
    type: number
    default: 600
  - name: 'APIM_SK'
    displayName: 'API-Key (NOT required for putTokenMockedPdv script)'
    type: string
    default: 'IGNORE_IF_putTokenMockedPdv'
  - name: 'SERVICE_ID'
    displayName: 'ServiceId (required for idpayOnboardingAPI script)'
    type: string
    default: 'IGNORE_IF_NOT_idpayOnboardingAPI'
  - name: 'INITIATIVE_ID'
    displayName: 'InitiativeId (required for ioPutEnrollInstrumentIssuer and ioPutEnrollIban script)'
    type: string
    default: 'IGNORE_IF_NOT_ioPutEnrollInstrumentIssuer_and_ioPutEnrollIban'
  - name: 'TRX_FOR_VU'
    displayName: 'Number of transaction for VUs'
    type: number
    default: 1
  - name: 'RTD_API_KEY'
    displayName: 'RTD API-Key'
    type: string
    default: 'IGNORE_IF_NOT_NECESSARY'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(pythonVersion)'
    displayName: 'Use Python $(pythonVersion)'
  - task: DownloadSecureFile@1
    name: rtd_uat_acquirer_mauth_pem
    displayName: 'RTD Certification File'
    inputs:
      secureFile: 'rtd-uat-acquirer-mauth.pem'
  - task: DownloadSecureFile@1
    name: rtd_uat_acquirer_mauth_key
    displayName: 'RTD Key File'
    inputs:
      secureFile: 'rtd-uat-acquirer-mauth.key'
  - task: DownloadSecureFile@1
    name: bpd_pm_test
    displayName: 'Download BPD PM public uat'
    inputs:
      secureFile: 'Centrostella-BPD-PM-TEST_0xE7D22349_public_uat.asc'
  - script: |
      mkdir $(pwd)/certs
    displayName: Create Certs Folder
  - script: |
      cp /home/vsts/work/_temp/rtd-uat-acquirer-mauth.pem $(pwd)/certs/rtd-uat-acquirer-mauth.pem
    displayName: Copy RTD PEM File
  - script: |
      cp /home/vsts/work/_temp/rtd-uat-acquirer-mauth.key $(pwd)/certs/rtd-uat-acquirer-mauth.key
    displayName: Copy RTD Key File
  - script: |
      python -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip
    workingDirectory: $(projectRoot)
    displayName: "Install CLI requirements"
  - script: |
      curl -L https://github.com/pagopa/cstar-cli/archive/refs/heads/main.zip -o cstar-cli.zip
      unzip cstar-cli.zip
      cd cstar-cli-main 
      chmod +rwx ../install.sh
      ../install.sh
    displayName: Set environment
  #TODO set date time parameters
  - script: |
      sudo apt install rename
      cst idpay idpaydataset --action dataset_and_transactions --env ${{ parameters.TARGET_ENV }} --api-key ${{ parameters.RTD_API_KEY }} --key $(rtd_uat_acquirer_mauth_key.secureFilePath) --cert $(rtd_uat_acquirer_mauth_pem.secureFilePath) --PM-pubk $(bpd_pm_test.secureFilePath) --out-dir ./generated --num-fc ${{ parameters.VIRTUAL_USERS_ENV }} --trx-per-fc 1 --start-datetime 2023-02-06T20:30:00.000Z --mcc 1234 --PM-salt SALT123
      cp ./generated/*/* ./assets
      ls -lrt ./assets
      cd ./assets
      ls -lrt
      rename -v 's/(\.\d+)+//.pgp' *.pgp
    displayName: Retrieve resource from cstar-cli
  - script: |
       docker pull grafana/k6:latest
    displayName: Pull k6 image
  - script: |
      ls -lrt $(pwd)
      docker run -i \
        --name ksixtests \
        --user $UID \
        -v $(pwd):/app \
        --workdir "/app" \
        -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
        -e SCENARIO_TYPE_ENV=${{ parameters.SCENARIO_TYPE_ENV }} \
        -e VIRTUAL_USERS_ENV=${{ parameters.VIRTUAL_USERS_ENV }} \
        -e STAGE_NUMBER_ENV=${{ parameters.STAGE_NUMBER_ENV }} \
        -e DURATION_PER_VU_ITERATION=${{ parameters.DURATION_PER_VU_ITERATION }} \
        -e APIM_SK=${{ parameters.APIM_SK }} \
        -e SERVICE_ID=${{ parameters.SERVICE_ID }} \
        -e INITIATIVE_ID=${{ parameters.INITIATIVE_ID }} \
        grafana/k6:latest \
        run /app/test/performance/${{ parameters.SCRIPT }}.js
    displayName: Run k6 ${{ parameters.SCRIPT }}
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/performancetest-result.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true

