# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: 'SCRIPT'
    displayName: 'Script name'
    type: string
    values:
      - putTokenMockedPdv
  - name: 'TARGET_ENV'
    displayName: 'Target Environment'
    type: string
    default: 'uat'
    values:
      - 'dev'
      - 'uat'

steps:
  - script: |
       docker pull grafana/k6:latest
    displayName: Pull k6 image
  - script: |
      pwd
      ls -lrt
      docker run -i \
        -v $(pwd):/ \
        -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
        grafana/k6:latest \
        run /test/performance/${{ parameters.SCRIPT }}.js
    displayName: Run k6 ${{ parameters.SCRIPT }}

