# Run Automated Test in UAT environment

trigger: none

pool:
  vmImage: ubuntu-22.04

parameters:
  - name: 'SCRIPT'
    displayName: 'Script name'
    type: string
    values:
      - putTokenMockedPdv
  - name: 'TARGET_ENV'
    displayName: 'Target Environment'
    type: string
    default: 'uat'
    values:
      - 'dev'
      - 'uat'
  - name: 'SCENARIOTYPE_ENV'
    displayName: 'Scenario type'
    type: string
    default: 'ramping-arrival-rate'
    values:
      - 'ramping-arrival-rate'
      - 'per-vu-iterations'
  - name: 'VIRTUALUSERSR_ENV'
    displayName: 'Number of virtual users (1 - 100 000)'
    type: number
  - name: 'TRXFORVU_ENV'
    displayName: 'Number of transactions for each virtual user'
    type: number
    default: 1

steps:
  - script: |
       docker pull grafana/k6:latest
    displayName: Pull k6 image
  - script: |
      docker run -i \
        --name ksixtests \
        --user $UID \
        -v $(pwd):/app \
        --workdir "/app" \
        -e TARGET_ENV=${{ parameters.TARGET_ENV }} \
        grafana/k6:latest \
        run /app/test/performance/${{ parameters.SCRIPT }}.js
    displayName: Run k6 ${{ parameters.SCRIPT }}
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/performancetest-result.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'
      failTaskOnFailedTests: true

